### ISSUE TITLE
Details on what makes FAR v0.16.0.2 incompatible

### ISSUE THREAD

**Issue by bverh** [alobazombie/kOS-Ferram#2] opened 2021-06-06 22:09 UTC
Hi,

Just wondering what the main issues are and if there are plans to fix. I would be happy to take a crack at it. 

Specifically, for your Shuttle Entry Sim - I noticed the only method you call from kOS-Ferram in that example is AEROFORCEAT, which is linked to the CalculateVesselAeroForces method in the FAR API. That method doesn't seem to have changed from v0.16.0.1 to v0.16.0.2 so I can't really pin down what exactly is incompatible. 

I tried recompiling kOS-Ferram using v0.16.0.2 just to see if it would work, and I run into the "120deg" bank angle issue (which you pointed out in the Youtube video comments is an issue with v0.16.0.2). 

Would appreciate some guidance / background if you have more details so I can try to make a PR :)

**Comment by giuliodondi** [comment] 2021-06-06 22:56
Hi,

The issue is exactly the same one reported for Trajectories: the estimated drag force by CalculateVesselAeroForces is almost negligible and thus all reentry predictions fail.

The issue seems to have been a bug in some unit conversion done internally by FAR, it has been reported at https://github.com/dkavolis/Ferram-Aerospace-Research/issues/113
The issue sems to have already been fixed in commit 135bb12 but this is not part of the latest release.

Since it's a bug with FAR I'd like not to touch anything in my own interface, as any changes are likely to become moot once the next release is rolled out.
If you feel like installing FAR 0.16.0.2 manually, you'll have to pull from somewhere downstream of that commit. If you want to stick to CKAN you'll have to use 0.16.0.1

**Comment by bverh** [comment] 2021-06-06 23:21
Looks like it was that in combination with this issue as well : https://github.com/dkavolis/Ferram-Aerospace-Research/issues/111

I think your interface is OK once they release the next FAR version. Thanks for taking a look!

**Closed as completed** 2023-11-22 19:56 UTC
